version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: imalamin/flask:1.0.0-alpine
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:80"
    networks:
      - myn

# Default settings -> load balanced overlay network
networks:
  myn: